name: 'RSpec'
description: 'Run RSpecs'

inputs:
  registry:
    description: 'Registry to get image'
    required: false
    default: ghcr.io
  username:
    description: 'Registry login username'
    required: true
  password:
    description: 'Registry login password'
    required: true
  bundle_dockerfile_name:
    description: 'dockerfile name, used in bundle build'
    required: false
    default: Dockerfile
  test_dockerfile_name:
    description: 'dockerfile name, used in test build'
    required: false
    default: Dockerfile
  git_patoken:
    description: 'git personal access token'
    required: false
  platforms:
    description: 'platforms to build'
    required: false
    default: linux/amd64,linux/arm64
  repo_owner:
    description: 'Repo owner to push to'
    required: false
    default: codeboxxtechschool
  push_dir:
    description: 'directory to push to'
    required: true
  branch:
    description: 'branch for tag'
    required: true
  version:
    description: 'version for tag'
    required: true
  bundle_required_files:
    description: 'files that require bundle'
    required: false
  image_base:
    description: 'Image from which to bundle on'
    required: false
    default: cg/java-dev-capy-webkit

#    push_directory: cg/customer/test
#    branch: ${{ steps.extract_branch.outputs.branch }}
#    version: latest

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # OR "2"
    - name: Get changed files
      id: changed_files
      uses: tj-actions/changed-files@v2.0.0
      with:
        files: |
          Gemfile.lock
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: "setup image ref"
      shell: bash
      run: |
        echo "REPO_PATH=${{ inputs.registry }}/${{ inputs.repo_owner }}/${{ inputs.push_dir }}" >> $GITHUB_ENV
        echo "TAG_LEAF=${{ inputs.branch }}:${{ inputs.version }}" >> $GITHUB_ENV
        echo "BUNDLE_TAG=${{ env.REPO_PATH }}/bundle/${{ env.TAG_LEAF }}" >> $GITHUB_ENV
    - name: Build and push bundle
      if: ${{steps.changed_files.outputs.only_changed == 'true'}}
      uses: docker/build-push-action@v2
      with:
        secrets: |
          GIT_PAT=${{ inputs.git_patoken }}
        file: ${{ inputs.bundle_dockerfile_name }}
        platforms: ${{ inputs.platforms }}
        build-args: |
          IMAGE_REF=${{ env.REPO_PATH }}/${{ inputs.image_base }}
        push: true
        tags: |
          ${{ env.BUNDLE_TAG }}
    - name: Build and push for tests
      uses: docker/build-push-action@v2
      with:
        secrets: |
          GIT_PAT=${{ inputs.git_patoken }}
        file: ${{ inputs.test_dockerfile_name }}
        platforms: ${{ inputs.platforms }}
        build-args: |
          IMAGE_REF=${{ env.BUNDLE_TAG }}
        push: true
        tags: |
          ${{ env.REPO_PATH }}/${{ env.TAG_LEAF }}
